version: 0.2

env:
  parameter-store:
    REPOSITORY_URI: /jenkins-server-pipeline/RepositoryURI

phases:
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=lts}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:lts -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI