# Config for AWS S3 artifact storage plugin
aws:
  awsCredentials:
    region: "us-west-2"
  s3:
    container: "o3de-jenkins-artifacts"
unclassified:
  artifactManager:
    artifactManagerFactories:
    - jclouds:
        provider: "s3"
