# Config for Build Failure Analyzer plugin
# See: https://plugins.jenkins.io/build-failure-analyzer/
unclassified:
  buildFailureAnalyzer:
    gerritTriggerEnabled: true
    globalEnabled: true
    knowledgeBase:
      mongoDB:
        dbName: "build-failure-rca"
        enableStatistics: true
        host: ${/jenkins/config/buildFailureDB/host}
        password: ${/jenkins/config/buildFailureDB/password}
        port: 27017
        successfulLogging: false
        userName: ${/jenkins/config/buildFailureDB/username}
    maxLogSize: 0
    noCausesEnabled: true
    noCausesMessage: "No problems were identified. If you know why this problem occurred,\
      \ please add a suitable Cause for it."
    nrOfScanThreads: 3
