# Config for Jenkins credentials
# Do not add credential values directly to this file.
# Credentials pulled from SSM
# See: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc 
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "build_node_credentials"
          privateKeySource:
            directEntry:
              privateKey: ${/jenkins/config/buildnode/privatekey}
          scope: GLOBAL
          username: ${/jenkins/config/buildnode/username}
      - usernamePassword:
          id: "github-access-token"
          password: ${/jenkins/config/github/accesstoken}
          scope: GLOBAL
          username: ${/jenkins/config/github/username}
      - usernamePassword:
          id: "jenkins-service-user"
          password: ${/jenkins/config/serviceuser/password}
          scope: GLOBAL
          username: ${/jenkins/config/serviceuser/username}
