# Config for Jenkins credentials
# Do not add credential values directly to this file.
# Credentials pulled from SSM
# See: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc 
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "lybuilder"
          privateKeySource:
            directEntry:
              privateKey: ${/jenkins/config/buildnode/privatekey}
          scope: GLOBAL
          username: "lybuilder"
      - usernamePassword:
          id: "o3de-ci-bot"
          password: ${/jenkins/config/github/token}
          scope: GLOBAL
          username: ${/jenkins/config/github/username}
      - usernamePassword:
          id: "build-failure-rca-kb"
          password: ${/jenkins/config/buildFailureDB/password}
          scope: GLOBAL
          username: ${/jenkins/config/buildFailureDB/username}
