# Config for Jenkins global environment variables
jenkins:
  globalNodeProperties:
  - envVars:
      env:
      - key: "BRANCH_DEFAULT"
        value: "development"
      - key: "CPACK_UPLOAD_URL"
        value: "s3://o3de-prism-prod-us-west-2"
      - key: "DEFAULT_REPOSITORY_NAME"
        value: "o3de"
      - key: "ES_HOSTS"
        value: "\"https://prod.mars.agscollab.com:443\""
      - key: "GITHUB_USER"
        value: "o3de-ci-bot"
      - key: "INSTALLER_BUCKET"
      - key: "INSTALLER_DOWNLOAD_URL"
        value: "https://www.o3debinaries.org"
      - key: "IS_UPLOAD_AP_LOGS"
        value: "True"
      - key: "IS_UPLOAD_TEST_ARTIFACTS"
        value: "True"
      - key: "JENKINS_ARTIFACTS_S3_BUCKET"
        value: "o3de-jenkins-artifacts"
      - key: "LFS_URL"
        value: "d3df09qsjufr6g.cloudfront.net/api/v1"
      - key: "LY_PACKAGE_SERVER_URLS"
        value: "s3://o3de-prod-3p-packages;"
      - key: "MARS_REPO"
        value: "https://github.com/aws-lumberyard/o3de-mars.git"
      - key: "POST_AR_BUILD_SNS_TOPIC"
        value: "arn:aws:sns:us-west-2:206706238973:post-ar-build"
      - key: "SERVICE_USER"
        value: "jenkins-service-user"
      - key: "SNS_TOPIC"
        value: "arn:aws:sns:us-west-2:206706238973:pipeline-notifications"
      - key: "SNS_TOPIC_BUILD_FAILURE"
        value: "arn:aws:sns:us-west-2:206706238973:create-github-issue"
      - key: "TEST_IMPACT_S3_BUCKET"
        value: "o3de-tiaf"
      - key: "TEST_IMPACT_WIN_BINARY"
        value: "c:\\\\ly\\\\3rdParty\\\\packages\\\\OpenCppCoverage\\\\Binary\\\\\
          windows-x64\\\\OpenCppCoverage.exe"
      - key: "TEST_SCREENSHOT_BUCKET"
        value: "jenkins-o3de-test-screenshots""s3://o3de-prism-prod-us-west-2"
