# Config for Project-based Matrix Authorization Strategy
# Default admin role granted in jenkins.yaml
jenkins:
  authorizationStrategy:
    projectMatrix:
      permissions:
      # Admin
      - "USER:Overall/Administer:admin"
      - "GROUP:Overall/Administer:o3de*aws-ops"
      # O3DE Groups
      - "GROUP:Job/Build:o3de*maintainers"
      - "GROUP:Job/Cancel:o3de*maintainers"
      - "GROUP:Job/Read:o3de*maintainers"
      - "GROUP:Overall/Read:o3de*maintainers"
      - "GROUP:View/Read:o3de*maintainers"
      - "GROUP:Job/Build:o3de*reviewers"
      - "GROUP:Job/Cancel:o3de*reviewers"
      - "GROUP:Job/Read:o3de*reviewers"
      - "GROUP:Overall/Read:o3de*reviewers"
      - "GROUP:View/Read:o3de*reviewers"
      - "GROUP:Job/Build:o3de*sig-build-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-build-maintainers"
      - "GROUP:Job/Read:o3de*sig-build-maintainers"
      - "GROUP:Overall/Read:o3de*sig-build-maintainers"
      - "GROUP:View/Read:o3de*sig-build-maintainers"
      - "GROUP:Job/Build:o3de*sig-content-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-content-maintainers"
      - "GROUP:Job/Read:o3de*sig-content-maintainers"
      - "GROUP:Overall/Read:o3de*sig-content-maintainers"
      - "GROUP:View/Read:o3de*sig-content-maintainers"
      - "GROUP:Job/Build:o3de*sig-core-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-core-maintainers"
      - "GROUP:Job/Read:o3de*sig-core-maintainers"
      - "GROUP:Overall/Read:o3de*sig-core-maintainers"
      - "GROUP:View/Read:o3de*sig-core-maintainers"
      - "GROUP:Job/Build:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Job/Read:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Overall/Read:o3de*sig-graphics-audio-maintainers"
      - "GROUP:View/Read:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Job/Build:o3de*sig-network-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-network-maintainers"
      - "GROUP:Job/Read:o3de*sig-network-maintainers"
      - "GROUP:Overall/Read:o3de*sig-network-maintainers"
      - "GROUP:View/Read:o3de*sig-network-maintainers"
      - "GROUP:Job/Build:o3de*sig-operations-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-operations-maintainers"
      - "GROUP:Job/Read:o3de*sig-operations-maintainers"
      - "GROUP:Overall/Read:o3de*sig-operations-maintainers"
      - "GROUP:View/Read:o3de*sig-operations-maintainers"
      - "GROUP:Job/Build:o3de*sig-platform-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-platform-maintainers"
      - "GROUP:Job/Read:o3de*sig-platform-maintainers"
      - "GROUP:Overall/Read:o3de*sig-platform-maintainers"
      - "GROUP:View/Read:o3de*sig-platform-maintainers"
      - "GROUP:Job/Build:o3de*sig-release-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-release-maintainers"
      - "GROUP:Job/Read:o3de*sig-release-maintainers"
      - "GROUP:Overall/Read:o3de*sig-release-maintainers"
      - "GROUP:View/Read:o3de*sig-release-maintainers"
      - "GROUP:Job/Build:o3de*sig-simulation-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-simulation-maintainers"
      - "GROUP:Job/Read:o3de*sig-simulation-maintainers"
      - "GROUP:Overall/Read:o3de*sig-simulation-maintainers"
      - "GROUP:View/Read:o3de*sig-simulation-maintainers"
      - "GROUP:Job/Build:o3de*sig-testing-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-testing-maintainers"
      - "GROUP:Job/Read:o3de*sig-testing-maintainers"
      - "GROUP:Overall/Read:o3de*sig-testing-maintainers"
      - "GROUP:View/Read:o3de*sig-testing-maintainers"
      - "GROUP:Job/Build:o3de*sig-build-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-build-reviewers"
      - "GROUP:Job/Read:o3de*sig-build-reviewers"
      - "GROUP:Overall/Read:o3de*sig-build-reviewers"
      - "GROUP:View/Read:o3de*sig-build-reviewers"
      - "GROUP:Job/Build:o3de*sig-content-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-content-reviewers"
      - "GROUP:Job/Read:o3de*sig-content-reviewers"
      - "GROUP:Overall/Read:o3de*sig-content-reviewers"
      - "GROUP:View/Read:o3de*sig-content-reviewers"
      - "GROUP:Job/Build:o3de*sig-core-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-core-reviewers"
      - "GROUP:Job/Read:o3de*sig-core-reviewers"
      - "GROUP:Overall/Read:o3de*sig-core-reviewers"
      - "GROUP:View/Read:o3de*sig-core-reviewers"
      - "GROUP:Job/Build:o3de*sig-docs-community-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-docs-community-reviewers"
      - "GROUP:Job/Read:o3de*sig-docs-community-reviewers"
      - "GROUP:Overall/Read:o3de*sig-docs-community-reviewers"
      - "GROUP:View/Read:o3de*sig-docs-community-reviewers"
      - "GROUP:Job/Build:o3de*sig-docs-community-site-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-docs-community-site-reviewers"
      - "GROUP:Job/Read:o3de*sig-docs-community-site-reviewers"
      - "GROUP:Overall/Read:o3de*sig-docs-community-site-reviewers"
      - "GROUP:View/Read:o3de*sig-docs-community-site-reviewers"
      - "GROUP:Job/Build:o3de*sig-graphics-audio-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-graphics-audio-reviewers"
      - "GROUP:Job/Read:o3de*sig-graphics-audio-reviewers"
      - "GROUP:Overall/Read:o3de*sig-graphics-audio-reviewers"
      - "GROUP:View/Read:o3de*sig-graphics-audio-reviewers"
      - "GROUP:Job/Build:o3de*sig-platform-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-platform-reviewers"
      - "GROUP:Job/Read:o3de*sig-platform-reviewers"
      - "GROUP:Overall/Read:o3de*sig-platform-reviewers"
      - "GROUP:View/Read:o3de*sig-platform-reviewers"
      - "GROUP:Job/Build:o3de*sig-release-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-release-reviewers"
      - "GROUP:Job/Read:o3de*sig-release-reviewers"
      - "GROUP:Overall/Read:o3de*sig-release-reviewers"
      - "GROUP:View/Read:o3de*sig-release-reviewers"
      - "GROUP:Job/Build:o3de*sig-simulation-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-simulation-reviewers"
      - "GROUP:Job/Read:o3de*sig-simulation-reviewers"
      - "GROUP:Overall/Read:o3de*sig-simulation-reviewers"
      - "GROUP:View/Read:o3de*sig-simulation-reviewers"
      - "GROUP:Job/Build:o3de*sig-testing-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-testing-reviewers"
      - "GROUP:Job/Read:o3de*sig-testing-reviewers"
      - "GROUP:Overall/Read:o3de*sig-testing-reviewers"
      - "GROUP:View/Read:o3de*sig-testing-reviewers"
      # O3DE Bots
      - "GROUP:Job/Build:o3de*bots"
      - "GROUP:Job/Cancel:o3de*bots"
      - "GROUP:Job/Read:o3de*bots"
      - "GROUP:Overall/Read:o3de*bots"
      - "GROUP:Run/Update:o3de*bots"
      - "GROUP:View/Read:o3de*bots"
      # Public read access
      - "USER:Overall/Read:anonymous"
      - "GROUP:Overall/Read:authenticated"
