# Config for Project-based Matrix Authorization Strategy
# Default admin role granted in jenkins.yaml
jenkins:
  authorizationStrategy:
    projectMatrix:
      permissions:
      # Admin
      - "USER:Overall/Administer:admin"
      - "GROUP:Overall/Administer:o3de*aws-ops"
      # O3DE Groups
      - "GROUP:Job/Build:o3de*maintainers"
      - "GROUP:Job/Cancel:o3de*maintainers"
      - "GROUP:Job/Read:o3de*maintainers"
      - "GROUP:Overall/Read:o3de*maintainers"
      - "GROUP:View/Read:o3de*maintainers"
      - "GROUP:Job/Build:o3de*reviewers"
      - "GROUP:Job/Cancel:o3de*reviewers"
      - "GROUP:Job/Read:o3de*reviewers"
      - "GROUP:Overall/Read:o3de*reviewers"
      - "GROUP:View/Read:o3de*reviewers"
      - "GROUP:Job/Build:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Job/Cancel:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Job/Read:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Overall/Read:o3de*sig-graphics-audio-maintainers"
      - "GROUP:View/Read:o3de*sig-graphics-audio-maintainers"
      - "GROUP:Job/Build:o3de*sig-graphics-audio-reviewers"
      - "GROUP:Job/Cancel:o3de*sig-graphics-audio-reviewers"
      - "GROUP:Job/Read:o3de*sig-graphics-audio-reviewers"
      - "GROUP:Overall/Read:o3de*sig-graphics-audio-reviewers"
      - "GROUP:View/Read:o3de*sig-graphics-audio-reviewers"
      # O3DE Bots
      - "GROUP:Job/Build:o3de*bots"
      - "GROUP:Job/Cancel:o3de*bots"
      - "GROUP:Job/Read:o3de*bots"
      - "GROUP:Overall/Read:o3de*bots"
      - "GROUP:Run/Update:o3de*bots"
      - "GROUP:View/Read:o3de*bots"
      # Public read access
      - "USER:Overall/Read:anonymous"
      - "GROUP:Overall/Read:authenticated"
